// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzIKy7wUlKTXUMC8mMjMeo-Mzreck_36U',
    appId: '1:778807693048:web:0aee001f2c710265c9750d',
    messagingSenderId: '778807693048',
    projectId: 'da-lttbdd',
    authDomain: 'da-lttbdd.firebaseapp.com',
    storageBucket: 'da-lttbdd.firebasestorage.app',
    measurementId: 'G-WXGB73WVH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDffnnk9PhRHadiprGv80FOnXDmuGzJAFk',
    appId: '1:778807693048:android:043f60fc9b07c0dac9750d',
    messagingSenderId: '778807693048',
    projectId: 'da-lttbdd',
    storageBucket: 'da-lttbdd.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzIKy7wUlKTXUMC8mMjMeo-Mzreck_36U',
    appId: '1:778807693048:web:0aee001f2c710265c9750d',
    messagingSenderId: '778807693048',
    projectId: 'da-lttbdd',
    authDomain: 'da-lttbdd.firebaseapp.com',
    storageBucket: 'da-lttbdd.firebasestorage.app',
    measurementId: 'G-WXGB73WVH1',
  );
}
